### ISSUE TITLE
Compare emissions by type to car emissions

### ISSUE THREAD

**Issue by vinaydixit** [cityenergyproject/seattle#147]
investigate a 'lay' data layer, eg number of cars equivalent metric. Eric to lead; additional contrast and labeling issues to be addressed by Amira (we can create a separate issue if needed).

**Comment by ebrelsford** [comment]
@seattle-benchmarking We're currently using 4.7 metric tons as a passenger vehicle's use for one year, is that still accurate?

**Comment by ebrelsford** [comment]
Maybe we could do something like this for the text about cars:

![image](https://user-images.githubusercontent.com/375002/70576652-7834b600-1b77-11ea-9df6-e088f7163458.png)

**Comment by seattle-benchmarking** [comment]
@ebrelsford  Two comments from Rebecca on the new fuel use vs emissions bars:
1 - the yellow text is hard to read (steam). anything we can do about that? It's not too bad on screen but gets worse on print
2 - the bars feel different in style than the rest of the page, probably since so much of our other graphics use bold colors sparingly to highlight the building in question. but this whole graphic uses the bold colors. not sure this is necessarily bad but might explore either (a) reducing the height of the bar to minimize this feel or (2) use a slightly less bold version of the colors. 
![image](https://user-images.githubusercontent.com/58457382/70735528-47fa2e00-1cc3-11ea-85f4-8027578a8fc0.png)
