### ISSUE TITLE
Look at how no-data situations are handled

### ISSUE THREAD

**Issue by vinaydixit** [cityenergyproject/seattle#151]
need consistent messaging, better wording and expected behavior.

**Comment by ebrelsford** [comment]
@seattle-benchmarking I believe this is mostly taken care of, but are there specific situations that you would like us to take a look at?

**Comment by ebrelsford** [comment]
Check on common times when there will not be data available:
 * [x] energy star
 * [x] trends chart (if it's a new building)

**Comment by ebrelsford** [comment]
Energy star says "Energy Star Score data not available" in both popup and on scorecard.

**Comment by seattle-benchmarking** [comment]
@ebrelsford A few minor changes to wording for the errors if you don't mind:

- [x] If no ENERGY STAR score - change from "ENERGY STAR Score data not available" to "We don't have an ENERGY STAR score for this building for this year. Contact energybenchmarking@seattle.gov if this is incorrect."

- [x] Seeing some odd behavior when missing a year of data in the trends. I can try to clean some of these up in the data but might need a better solution:
![image](https://user-images.githubusercontent.com/58457382/71016730-6e94dc00-20aa-11ea-8009-c5edf98fce4a.png)

https://cityenergyproject.github.io/seattle/#seattle/2018?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.60810&lng=-122.33216&zoom=14&building=18&report_active=true 

- [x] Missing EUI for a year - see building ID = 215. Even though the building has some data for 2015-2017, no scorecard will display even just the building name/details header. I'm guess this is caused by missing EUI data for 2018 but not sure.

https://cityenergyproject.github.io/seattle/#seattle/2015?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.54968&lng=-122.31603&zoom=14&building=215&report_active=true

**Comment by seattle-benchmarking** [comment]
@ebrelsford another example of missing EUI for one year in the Trend line:
https://cityenergyproject.github.io/seattle/#seattle/2018?categories[0][field]=property_type&categories[0][other]=false&categories[0][values][]=Small-+and+Mid-Sized+Office&layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61167&lng=-122.32028&zoom=15&building=839&report_active=true

Perhaps we can just set 0s to null to avoid the weird line. Not sure this would work if a missing value was 2015 or 2018 though?

**Comment by ebrelsford** [comment]
@seattle-benchmarking I'd appreciate it if we could keep these as separate issues as some of them have different causes and bundling them here can make it difficult to track.

As for building ID 215, this isn't because of the year data, it's because it doesn't have a property type:

![image](https://user-images.githubusercontent.com/375002/71026033-520e9900-20d6-11ea-9706-d7aaf3d7ab22.png)

**Comment by seattle-benchmarking** [comment]
@ebrelsford Can you copy the new ENERGY STAR text to the EUI situations too?

We don't have an EUI for this building for this year. Contact energybenchmarking@seattle.gov if this is incorrect.

![image](https://user-images.githubusercontent.com/58457382/71196273-94ee7f00-2244-11ea-8368-00a297ad2c8a.png)

**Comment by ebrelsford** [comment]
@seattle-benchmarking Done!
