### ISSUE TITLE
4 - Building footprints 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#52]
Add building footprint outlines to map and alter highlight level of detail depending on zoom level

**Comment by almccon** [comment]
I'll hang onto this issue for now @sconnelley. Still awaiting the footprint data, and still need to figure out exactly how we'd change our map styling to accommodate it.

**Comment by almccon** [comment]
We now have building footprint data in CARTO. It contains a `buildingid` field which matches the `id` field in the energy benchmarking data.
It also seems to include a flag `inebr2016` which tells whether or not that building has energy data in 2016. 

![screen shot 2017-05-18 at 2 48 41 pm](https://cloud.githubusercontent.com/assets/1212178/26225743/9d4eb25a-3bdd-11e7-9840-02c34e9ca778.png)

since most buildings don't have energy data, we don't need to show them on the map (I assume?). So this might mean we won't have to worry about map performance coming from CARTO, and we can stick with the same raster rendering approach (instead of switching to something with higher performance like MapboxGL). 

We still need some CartoCSS fiddling with the style to make sure the buildings are still visible when you zoom out (probably transition back to using dots at some zoom levels)

Here are the buildings joined to the data, styled according to site EUI 2016. This is just with styling applied in CARTO, so the class breaks and colors aren't exactly right.

![screen shot 2017-05-18 at 2 44 54 pm](https://cloud.githubusercontent.com/assets/1212178/26225793/d15844a8-3bdd-11e7-8654-a02e6627e656.png)

**Comment by emilyhobson** [comment]
Whats the reamining scope of work on this, @almccon ?

**Comment by almccon** [comment]
- [ ] Prototype a map in CARTO that has satisfying zoom-level transitions between dots and polygons for the buildings. Maybe the dots will also change size a bit as they start to transition into polygons? Maybe the polygons need a really thick border that will look more or less like a dot when we're zoomed far out? This is 2-4 hours of work.
- [x] Wire up the application to draw building polygons sometimes instead of always just dots. Needs a bit of investigation into the parts of the code where we generate the CartoCSS. Possibly this will be very easy, but it could also be tricky. More uncertainty here, so maybe 2-8 hours.

**Comment by almccon** [comment]
@sconnelley, Emily says you may have capacity to do this in the next few weeks. You could do the second checkbox first (just switching the CartoCSS code to use polygons instead of points).

**Comment by sconnelley** [comment]
@almccon I have started on checkbox 2.  Are you thinking on lower zooms use dots and on higher zooms use footprints?

**Comment by almccon** [comment]
Yeah, exactly. I just don't have an idea for what zoom level we should transition at. And no idea how graceful that transition will be.

**Comment by sconnelley** [comment]
@almccon I roughed in the footprint behavior you wrote up in the second checkbox above.  It still needs some more work:
- [x] integrate current CartoCSS
- [x] account for filters & categories
- [x] optimization / refinements

**Comment by almccon** [comment]
Currently looks like this, starting at z15:
![pasted image at 2017_06_26 04_05 pm](https://user-images.githubusercontent.com/1212178/27564736-979e9210-5a8e-11e7-8614-a0e7ff6ddb13.png)

Looks good!

I'm starting to have second thoughts about my idea for a smoother transition, which would've been to have a couple of in-between zooms (probably 13 and 14) where buildings had really thick outlines, making them feel kinda blobby and dot-like. Now I think that would just make the thing seem broken, instead of seeming like a continuous transition. 

So I suggest we move forward with this as-is, and keep the hard transition between dots at z14 and polgyons at z15. @sconnelley anything else you want to finish here, or can we close this?

**Comment by sconnelley** [comment]
@almccon Nothing else from me at this point
