### ISSUE TITLE
Feedback on build #2 - Regression test list 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#70]
https://drive.google.com/open?id=0B5tBIGe_xercQW9hTmNjZEotdGs

**Comment by nicolettehayes** [comment]
Feedback for scorecard (building report):

- [ ]  All uses of ENERGY STAR should be in all caps

- [ ] Include a trademark, ENERGY STAR® 
![screen shot 2017-07-31 at 12 14 04 pm](https://user-images.githubusercontent.com/12550451/28794058-dbc20596-75e9-11e7-806b-14fddac34522.png)

- [ ] Increase text size and line-spacing for description
 ![screen shot 2017-07-31 at 12 13 35 pm](https://user-images.githubusercontent.com/12550451/28794002-b5b91952-75e9-11e7-924e-82ac36ea0a85.png)

- [ ] Building type referenced in "compared to average" needs to be dynamic (display correct building type for each building): 
![screen shot 2017-07-31 at 12 19 55 pm](https://user-images.githubusercontent.com/12550451/28794261-95a82e0e-75ea-11e7-8002-b64f591fbb13.png)

- [ ] Address label overlap
![screen shot 2017-07-31 at 12 21 54 pm](https://user-images.githubusercontent.com/12550451/28794357-e98abe38-75ea-11e7-9784-3a3d28c0def2.png)

- [ ] always round EUI to one decimal place
![screen shot 2017-07-31 at 12 23 35 pm](https://user-images.githubusercontent.com/12550451/28794412-1fc5fe86-75eb-11e7-99ba-df3dc8a1f4fd.png)

- [ ] steam cuts off (tracked in #80)

- [ ] round usage TOTAL to whole number
![screen shot 2017-07-31 at 12 26 59 pm](https://user-images.githubusercontent.com/12550451/28794643-c4460ca8-75eb-11e7-8753-5c952eb44a9c.png)

- [ ] round emissions total to one decimal
![screen shot 2017-07-31 at 12 27 09 pm](https://user-images.githubusercontent.com/12550451/28794648-c831b0c4-75eb-11e7-8ad5-0a2b91d7815f.png)

- [ ] address overlap in Change from Last Year section
![screen shot 2017-07-31 at 12 30 44 pm](https://user-images.githubusercontent.com/12550451/28794726-1a1ff706-75ec-11e7-92ff-12788e76ff1a.png)

- [ ] show parcels outlines (instead of dots) sooner than zoom 15
![screen shot 2017-07-31 at 12 32 35 pm](https://user-images.githubusercontent.com/12550451/28794784-5ba2947c-75ec-11e7-9424-d42448c2bad0.png)

- [ ] handle building popups when no energy star score exists (see #84 )

**Comment by emilyhobson** [comment]
Duplicate to a bunch of other ones. Keep open to regress against.
