### ISSUE TITLE
Additional fields 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#8]
Addition of new building-specific data aspects such as postal code and owner comments. 

- [x] City of Seattle Benchmarking building ID
- [x] City of Seattle Building Type (NR, MF, K-12, Campus, Muni etc.)
- [x] Postal Code
- [x] Open "comments" field for owners/managers to provide information (use test data for comments until they deliver that data)
- [x] Multifamily Properties:
- [x] -- Number of Bedrooms - MF
- [x] --  Number of Floors - MF
- [x] --  Number of Units - MF

**Comment by emilyhobson** [comment]
Comments field isn't yet populated but we could explore test data

**Comment by almccon** [comment]
Do we have guidance about which of these should be shown by default in the popup, and which should be in the expanded view (after you click "read more")?

**Comment by almccon** [comment]
Also need to confirm: which field should we use to test for whether a building is a "Multifamily Property"? It looks like we could either look for "Multifamily Housing" in `primary_ptype_epa` or we could look for "Multifamily LR (1-4)" in `buildingtypename`. 

_Or_, we just show or hide those fields based on whether they're NULL or not. Will there be cases when a non-multifamily building will have multiple units? Or wouldn't there be times when you'd be interested in seeing the number of floors for a building that isn't multifamily?

**Comment by almccon** [comment]
Also, I don't see a "Number of Bedrooms" fields, but there is a "Number of Buildings" so I assume that's what we're talking about.

**Comment by almccon** [comment]
I added a new "comments" field in the database, and I populated it with "Test comment" for two buildings, the Magnolia United Church of Christ (the southwesternmost point in Magnolia) and Canterbury Shores Condominium (the northernmost point in Madison Park). I picked these two because they're easy to find them to click on.
![seattle_mouseover_comment](https://cloud.githubusercontent.com/assets/1212178/21574536/4100a496-cea9-11e6-8c43-61ca0d054d35.gif)

**Comment by almccon** [comment]
Now we have the multifamily-only fields showing up only at the right times. It requires that the "Multifamily Housing" is the value for `primary_ptype_epa` before it shows those fields.
![seattle_mouseover_multifamily](https://cloud.githubusercontent.com/assets/1212178/21599189/79860ac4-d11d-11e6-9f34-2cb83cc5602f.gif)

**Comment by almccon** [comment]
Note, I changed it so that you can check for multiple possible values in a field when choosing to suppress other fields. Specifically, it's not just "Multifamily Housing" that is the trigger to show the additional Number of Units fields (etc). Now any of these will do it: "High-Rise Multifamily","Mid-Rise Multifamily","Low-Rise Multifamily","Small- and Mid-Sized Office","Large Office","Medical Office"
